[package]
name = "db-api"
version = "0.1.0"
edition = "2021"


[dependencies]
ion-rs = "0.18.1"
core = { path = "../core" }

log.workspace = true
log4rs.workspace = true
image = "0.24.7"
chrono = "0.4.31"
